# ########################################################################
# language translated message text: $language{$land}{'A'}  (=Customer)
# You can simply add here your translation...
# ########################################################################
our %language = ('en' => {
                        'A' => 'Customer',
                        'B' => 'Notification Type',
                        'C' => 'Host Status',
                        'D' => 'Hostname',
                        'E' => 'Hostalias',
                        'F' => 'IP Address',
                        'G' => 'Hostgroup',
                        'H' => 'Event Time',
                        'I' => 'Host Output',
                        'J' => 'Author',
                        'K' => 'Comment',
                        'L' => 'Icinga2 Monitoring System Notification',
                        'M' => 'Generated by Icinga2'
                        },
                'pl' => {
                        'A' => 'Klient',
                        'B' => 'Typ Powiadomienia',
                        'C' => 'Status Hosta',
                        'D' => 'Nazwa Hosta',
                        'E' => 'Alias',
                        'F' => 'Adres IP',
                        'G' => 'Grupy',
                        'H' => 'Czas zdarzenia',
                        'I' => 'Host Output',
                        'J' => 'Autor',
                        'K' => 'Komentarz',
                        'L' => 'Icinga2 System monitorowania zdarzeń',
                        'M' => 'Wygenerowane przez system Icinga2'
                        },
                'fr' => {
                		'A' => 'Utilisateur',
                        'B' => 'Type de notification',
                        'C' => 'Statut d\'hôte',
                        'D' => 'Nom d\'hôte',
                        'E' => 'Alias d\'hôte',
                        'F' => 'Adresse IP',
                        'G' => 'Groupe d\'hôte',
                        'H' => 'Heure de la notification',
                        'I' => 'Données',
                        'J' => 'Auteur',
                        'K' => 'Commentaire',
                        'L' => 'Icinga2 Notification de la surveillance',
                        'M' => 'Généré par Icinga2'
                        },
                'de' => {
                		'A' => 'Anwender',
                        'B' => 'Nachrichtentyp',
                        'C' => 'Systemzustand',
                        'D' => 'Systemname',
                        'E' => 'Systemalias',
                        'F' => 'System IP Adresse',
                        'G' => 'Systemgruppe',
                        'H' => 'Meldungsdatum',
                        'I' => 'Systemnachricht',
                        'J' => 'Author',
                        'K' => 'Kommentar',
                        'L' => 'Icinga2 Überwachungssytem Meldung',
                        'M' => 'Erstellt mit Icinga2'
                        },
                'jp' => {
                		'A' => '顧客名',
                        'B' => '通知の種類',
                        'C' => 'ホストの状態',
                        'D' => 'ホスト名',
                        'E' => 'ホストの別名',
                        'F' => 'IPアドレス',
                        'G' => 'ホストグループ',
                        'H' => 'イベントの日付と時刻',
                        'I' => 'ホストデータ出力',
                        'J' => '投稿者',
                        'K' => 'コメント',
                        'L' => 'Icinga2 監視システムの通知',
                        'M' => 'このメーセジはオープンソースの監視システムIcinga2'
                        }
);